### ISSUE TITLE
Package won't install

### ISSUE THREAD

**Issue by prvst** [xlucpu/MOVICS#5]
Hi, I tried to install MOVICS but could not do it because one of the dependencies is now deprecated and not available for R's latest version.

`Error: Failed to install 'MOVICS' from GitHub:
  (converted from warning) package ‘SNFtool’ is not available for this version of R
`

The package SNFtool was removed from CRAN.

**Comment by xlucpu** [comment]
Hi,
Sorry I just noticed your message. Currently, please install SNFtool independently from installing MOVICS.
You can download the compressed file and install SNFtool locally (https://cran.r-project.org/src/contrib/Archive/SNFtool/), or use the following commond to install SNFtool in your R platform.
```
if (packageVersion("devtools") < 1.6) {
  install.packages("devtools")
}
devtools::install_github("maxconway/SNFtool")
```

I will update MOVICS to solve this issue ASAP.

Thank you for this.

**Comment by xlucpu** [comment]
I have updated the MOVICS (0.99.14) and please check if it can be installed.

**Comment by prvst** [comment]
Hi. Thanks for replying. I tried installing SNFTool manually as you said, but unfortunately, that also fails, see below:
```
ERROR: dependency ‘heatmap.plus’ is not available for package ‘SNFtool’
```

Apparently, heatmap.plus is also deprecated and removed from CRAN.

**Comment by xlucpu** [comment]
Dependencies must by installed when you have to install a package manually which means you have to install "heatmap.plus" first. If this package has other dependencies, you have to install them one by one manually. 

Anyway. I have updated MOVICS and please check if it can be installed now.

**Comment by prvst** [comment]
Sorry, still not able to install it.
`ERROR: dependencies ‘SNFtool’, ‘ridge’ are not available for package ‘MOVICS`

Also, the heatmap.plus package is not available anymore, not even in GitHub, so SNFTool cannot be installed.

**Comment by xlucpu** [comment]
I understand this situation. 

In this manner MOVICS can be only installed given that you have heatmap.plus installed already.
Therefore, please refer to https://cran.r-project.org/src/contrib/Archive/heatmap.plus/ and install heatmap.plus from local.

As for ridge package, please refer to ToubleShooting at the MOVICS main page. I summaried the solusion if you are using MacOS system.

Since MOVICS depends on a lot of external R package, I cannot make sure all these dependencies are constantly in maintain. Thus, the bottom line to get MOVICS installed is to make sure that you have all the dependencies installed.

**Comment by prvst** [comment]
Thanks. I had to go through a few other dependencies that are missing or not available, but after a couple of hours, I installed them.
