### ISSUE TITLE
Questions about how to install MOVICS on R 3.6.0

### ISSUE THREAD

**Issue by wu-yc** [xlucpu/MOVICS#6]
Hi Dr. Xiaofan,

MOVICS is fantastic. When installing this package, I am curious about how to install on R 3.6.0. Would you please offer some help?

Best,
Yingcheng

**Comment by xlucpu** [comment]
Hi Yingcheng,

Sorry there is no way to install MOVICS on R 3.6.0 because of several package dependencies. The minimal requirement for installing MOVICS needs R4.0.1.

Please note that, due to the removal of SNFtools from CRAN (no github storage for this package), please try to install SNFtools and its dependency manually first, then install MOVICS.

I will update this message ASAP.

Best,
Xiaofan Lu

**Comment by wu-yc** [comment]
Thanks for your fast reply. Now I have solved this by using the R 4. 

Cheers,
Yingcheng

**Comment by xlucpu** [comment]
Please be aware of the dependencies. I know it is hard but you have to make sure all the dependencies are correctly installed. Otherwise MOVICS would fail.

I then close this issue and good luck with your analysis.
