### ISSUE TITLE
Cannot install MOVICS in R 4.0.3

### ISSUE THREAD

**Issue by Charlesyip2016** [xlucpu/MOVICS#7]
Dr. XF:
I found that I cannot install MOVICS in my RStudio workstation. I tried many times, but I faced the same error is :

object 'geom_table' is not exported by 'namespace:ggpmisc'

How to solve this problems? please , thank you  !

**Comment by xlucpu** [comment]
Hi there, 

the latest version of ggpmisc is 0.3.9 and my ggpmisc hold the version of 0.3.6.

Since I cannot reproduce the error by my side, I simply suggest you uninstalled your ggpmisc and tried to install the old version (https://cran.r-project.org/src/contrib/Archive/ggpmisc/ggpmisc_0.3.6.tar.gz). 

See what happens then.

Best.

**Comment by Charlesyip2016** [comment]
Dear：
Thank you ! I install the latest version of ggpmisc is 0.4.0 and the geom_table function has changed .So I install the version 0.3.9. Now it works well. 
Best!
